"""adding new fields

Revision ID: 351477c86c04
Revises: 
Create Date: 2026-01-11 05:07:51.515369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351477c86c04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_vendor_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_issued_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('insurance_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sponsorship_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsorship_application', schema=None) as batch_op:
        batch_op.drop_column('logo_filename')
        batch_op.drop_column('support_level')

    with op.batch_alter_table('food_vendor_application', schema=None) as batch_op:
        batch_op.drop_column('insurance_filename')
        batch_op.drop_column('logo_filename')
        batch_op.drop_column('state_issued_id')

    # ### end Alembic commands ###
