"""adding proper timedate fields and image fields

Revision ID: 3e07fcaff642
Revises: 5a747345f6a4
Create Date: 2026-01-11 06:53:06.606765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e07fcaff642'
down_revision = '5a747345f6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_vendor_application', schema=None) as batch_op:
        batch_op.alter_column('vehicle_year',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('application_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('liability_application', schema=None) as batch_op:
        batch_op.alter_column('application_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liability_application', schema=None) as batch_op:
        batch_op.alter_column('application_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('food_vendor_application', schema=None) as batch_op:
        batch_op.alter_column('application_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('vehicle_year',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
