"""updating sponsor paid status

Revision ID: 5a747345f6a4
Revises: c8e90d28c744
Create Date: 2026-01-11 06:32:52.269472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a747345f6a4'
down_revision = 'c8e90d28c744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_vendor_application', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('signature_signed_at', sa.DateTime(), nullable=True))
        # batch_op.add_column(sa.Column('signature_ip', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=False, server_default='Pending'))

    with op.batch_alter_table('liability_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_signed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('signature_ip', sa.String(length=50), nullable=True))

    with op.batch_alter_table('sponsorship_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=False, server_default='Pending'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsorship_application', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    with op.batch_alter_table('liability_application', schema=None) as batch_op:
        batch_op.drop_column('signature_ip')
        batch_op.drop_column('signature_signed_at')

    with op.batch_alter_table('food_vendor_application', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('signature_ip')
        batch_op.drop_column('signature_signed_at')

    # ### end Alembic commands ###
