"""updating database

Revision ID: 7252bbf5e4a7
Revises: 
Create Date: 2026-01-14 16:18:47.553999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7252bbf5e4a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_vendor_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_window_location', sa.String(length=50), nullable=True),
    sa.Column('vehicle_make_model', sa.String(length=255), nullable=True),
    sa.Column('vehicle_year', sa.Integer(), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=255), nullable=True),
    sa.Column('drivers_license', sa.String(length=255), nullable=True),
    sa.Column('state_issued_id', sa.String(length=255), nullable=True),
    sa.Column('additional_vehicle_count', sa.Integer(), nullable=True),
    sa.Column('payment_cash', sa.Boolean(), nullable=False),
    sa.Column('payment_debit', sa.Boolean(), nullable=False),
    sa.Column('payment_visa', sa.Boolean(), nullable=False),
    sa.Column('payment_mastercard', sa.Boolean(), nullable=False),
    sa.Column('payment_amex', sa.Boolean(), nullable=False),
    sa.Column('payment_discover', sa.Boolean(), nullable=False),
    sa.Column('payment_other', sa.String(length=255), nullable=True),
    sa.Column('menu_item_1', sa.String(length=255), nullable=True),
    sa.Column('menu_item_2', sa.String(length=255), nullable=True),
    sa.Column('menu_item_3', sa.String(length=255), nullable=True),
    sa.Column('menu_item_4', sa.String(length=255), nullable=True),
    sa.Column('menu_item_5', sa.String(length=255), nullable=True),
    sa.Column('menu_item_6', sa.String(length=255), nullable=True),
    sa.Column('menu_item_7', sa.String(length=255), nullable=True),
    sa.Column('menu_item_8', sa.String(length=255), nullable=True),
    sa.Column('applicant_signature', sa.String(length=255), nullable=True),
    sa.Column('applicant_full_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('initials', sa.String(length=20), nullable=True),
    sa.Column('signature_signed_at', sa.DateTime(), nullable=True),
    sa.Column('signature_ip', sa.String(length=50), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('insurance_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('cell_phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liability_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('applicant_signature', sa.String(length=255), nullable=False),
    sa.Column('applicant_full_name', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('signature_signed_at', sa.DateTime(), nullable=True),
    sa.Column('signature_ip', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsorship_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_level', sa.String(length=50), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('cell_phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsorship_application')
    op.drop_table('liability_application')
    op.drop_table('food_vendor_application')
    # ### end Alembic commands ###
