"""udpating for admin login

Revision ID: c8e90d28c744
Revises: 351477c86c04
Create Date: 2026-01-11 05:30:39.208566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e90d28c744'
down_revision = '351477c86c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_vendor_application', schema=None) as batch_op:
        # Example: Setting the default to 'Pending' for existing rows
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='Pending'))

    with op.batch_alter_table('liability_application', schema=None) as batch_op:
        # Example: Setting the default to 'Pending' for existing rows
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='Pending'))

    with op.batch_alter_table('sponsorship_application', schema=None) as batch_op:
        # Example: Setting the default to 'Pending' for existing rows
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='Pending'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsorship_application', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('liability_application', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('food_vendor_application', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
